version: "3"
services:
  tasks_db:
    container_name: tasks_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: keyboardcat
      POSTGRES_DB: tasks
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 10
  api:
    container_name: tasks_api
    build: .
    restart: always
    ports:
      - 5001:5000
    depends_on:
      tasks_db:
        condition: service_healthy
    environment:
      DB_HOST: tasks_db
      DB_USER: postgres
      DB_PASSWORD: keyboardcat
      DB_NAME: tasks
      FLASK_ENV: production
